alias: Turn on lights when arriving home
initial_state: 'on'
hide_entity: True
trigger:
  platform: state
  entity_id: binary_sensor.smartthings_motionv4_0102c904_1_1280
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: time
      after: '18:45:00'
    - condition: state
      entity_id: 'device_tracker.cristian'
      state: 'not_home'
action:
  service: homeassistant.turn_on
  entity_id: group.arrival

