alias: Turn on bedroom lights
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.smartthings_motionv4_0107bf61_1_1280
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: time
      after: '17:00:00'
    - condition: template
      value_template: "{{ is_state('input_select.cristians_state', 'Awake') }}"
action:
  service: homeassistant.turn_on
  entity_id: group.bedroom_lights
