alias: Turn on the lights in the evening
initial_state: 'on'
hide_entity: True
trigger:
  platform: time
  at: '17:00:00'
condition:
    condition: state
    entity_id: 'device_tracker.cristian'
    state: 'home'
action:
  service: homeassistant.turn_on
  entity_id: group.lights_evening
