alias: Living room mode normal
initial_state: 'on'
hide_entity: True
trigger:
  event_data:
    command: button_single
    device_ieee: 28:6d:97:00:01:0d:34:5d
  event_type: zha_event
  platform: event
condition:
    condition: template
    value_template: "{{ is_state('input_select.living_room_lighting_state', 'Off') }}"
action:
  - service: scene.turn_on
    entity_id: scene.living_room_lighting_mode_normal
  - service: input_select.select_option
    data:
      entity_id: input_select.living_room_lighting_state
      option: Normal
