alias: Living room mode off
initial_state: 'on'
hide_entity: True
trigger:
  event_data:
    command: button_single
    device_ieee: 28:6d:97:00:01:0d:34:5d
  event_type: zha_event
  platform: event
condition:
    condition: template
    value_template: "{{ is_state('input_select.living_room_lighting_state', 'Romantic') }}"
action:
  - service: homeassistant.turn_off
    data:
      entity_id: group.living_room_lights
  - service: input_select.select_option
    data:
      entity_id: input_select.living_room_lighting_state
      option: Off
