alias: Turn on kettle in the evening
initial_state: 'on'
hide_entity: True
trigger:
  platform: time
  at: '05:55:00'
action:
  service: light.turn_on
  entity_id: light.centralite_4257050rzhac_04ae3ef2_1
