alias: Grind coffee on weekday mornings
initial_state: 'on'
trigger:
  platform: time
  at: '07:20:00'
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  service: script.grind_coffee
