alias: Turn off office lights
initial_state: 'on'
hide_entity: True
trigger:
  platform: state
  entity_id: binary_sensor.smartthings_motionv5_010acf87_1_1280
  to: 'off'
  for:
    minutes: 5
condition:
  condition: time
  after: '17:00:00'
action:
  service: homeassistant.turn_off
  entity_id: light.office_light
