alias: Toggle sleep mode awake
initial_state: 'on'
hide_entity: True
trigger:
  event_data:
    command: button_single
    device_ieee: 28:6d:97:00:01:05:55:1c 
  event_type: zha_event
  platform: event
condition:
    condition: template
    value_template: "{{ is_state('input_select.cristians_state', 'Asleep') }}"
action:
  - service: light.turn_on
    entity_id: group.bedroom_lights
  - service: input_select.select_option
    data:
      entity_id: input_select.cristians_state
      option: Awake
