sudo: false
dist: bionic
language: python
addons:
  apt:
    packages:
      - libudev-dev       # Zwave
python:
  - "3.7"
before_install:
  - mv travis/travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
