title: Home

resources:
  - url: /local/mini-graph-card-bundle.js?v=0.6.0
    type: module

views:
  # Home view
  - badges:
      - device_tracker.cristian
      - sensor.dark_sky_temperature
      - sensor.hall_temperature
    cards:
      - cards:
          - entities:
              - entity: light.ambient_light_counter
              - entity: light.ambient_light_tv
              - entity: light.ambient_light_wall
                name: Ambient Light (Wall)
              - entity: light.corner_light
              - entity: light.window_light
              - entity: light.table_light
              - entity: light.office_light
              - entity: light.bathroom_light
                name: Bathroom Light
              - entity: light.right_nightstand_light
              - entity: light.left_nightstand_light
            title: Lights
            type: entities
        type: vertical-stack
      - entity: weather.dark_sky
        type: weather-forecast
    icon: 'mdi:home'
    path: default_view
    title: default_view
  # Kitchen view
  - badges: []
    cards:
      - entity: light.centralite_4257050rzhac_04ae3ef2_1
        name: Kettle
        type: entity-button
        icon: 'mdi:power-plug'
      - entity: switch.osram_plug_01_00a26de0_3
        name: Nespresso
        type: entity-button
        icon: 'mdi:power-plug'
    icon: 'mdi:fridge'
    path: kitchen
    title: Kitchen
  # Bedroom view
  - badges: []
    cards:
      - entity: light.right_nightstand_light
        name: Right Nightstand
        type: light
      - entity: light.left_nightstand_light
        name: Left Nightstand
        theme: default
        type: light
    icon: 'mdi:hotel'
    path: bedroom
    title: Bedroom
  # Living Room View
  - badges: []
    cards:
      - entities:
          - entity: light.ambient_light_counter
          - entity: light.ambient_light_tv
          - entity: light.ambient_light_wall
            name: Ambient Light (Wall)
          - entity: light.corner_light
          - entity: light.window_light
        show_header_toggle: true
        title: Lights
        type: entities
      - entity: media_player.pioneer_avr
        type: media-control
      - entity: media_player.sony_bravia_tv
        type: media-control
      - entities:
          - light.corner_light
        type: picture-glance
        image: http://telepathic:8082/0/current.jpg
    icon: 'mdi:sofa'
    path: living_room
    title: Living Room
  # Office view
  - badges: []
    cards:
      - entity: light.office_light
        name: ' '
        type: light
      - entity: media_player.office_speaker
        type: media-control
    icon: 'mdi:desktop-mac'
    path: office
    title: Office
  # System view
  - badges: []
    cards:
      - entities:
        - sensor.uptime
        type: entities
      - cards:
        - entities:
          - entity: sensor.pi_hole_ads_blocked_today
          type: custom:mini-graph-card
          show:
            points: true
            labels: false
        - entities:
          - entity: sensor.speedtest_download
          - entity: sensor.speedtest_upload
          - entity: sensor.fast_com_download
          type: custom:mini-graph-card
        type: vertical-stack
      - entities:
        - entity: sensor.teksavvy_on_peak_download
          name: Download
        - entity: sensor.teksavvy_on_peak_upload
          name: Upload
        type: custom:mini-graph-card
        hours_to_show: 720
        points_per_hour: 0.05
        update_interval: 5
        name: Bandwidth Usage
        icon: 'mdi:cloud-download'
      - entities:
        - entity: sensor.hydroquebec_yesterday_total_consumption
        name: Power Consumption
        hours_to_show: 168
        points_per_hour: 0.0417
        type: custom:mini-graph-card
        show:
          graph: bar
      - entities:
        - entity: sensor.nas_fan_rpm
          icon: 'mdi:fan'
        - entity: sensor.nas_temp_value
          name: Overall Temp
        - entity: sensor.nas_uptime
          icon: 'mdi:av-timer'
        - entity: sensor.nas_vol_1_free
          icon: 'mdi:chart-donut'
          name: Vol 1 Free Space
        - entity: sensor.nas_vol_1_size
          icon: 'mdi:harddisk'
          name: Vol 1 Total Space
        - entity: sensor.nas_vol_2_free
          icon: 'mdi:chart-donut'
          name: Vol 2 Free Space
        - entity: sensor.nas_vol_2_size
          icon: 'mdi:harddisk'
          name: Vol 2 Total Space
        show_header_toggle: false
        title: Netgear ReadyNAS
        type: entities
    icon: 'mdi:settings'
    path: system
    title: System
