alias: Turn on lights when arriving home (state)
initial_state: 'on'
trigger:
  platform: state
  entity_id: 'device_tracker.cristian'
  to: 'home'
condition:
  condition: time
  after: '17:30:00'
action:
  service: homeassistant.turn_on
  entity_id: group.arrival
