alias: Turn on lights when arriving home (state)
initial_state: 'on'
trigger:
  platform: state
  entity_id: 'device_tracker.cristian'
  to: 'home'
condition:
  condition: template
  value_template: '{{ now().time().strftime("%T") > states("input_datetime.lighting_on_time") }}'
action:
  service: homeassistant.turn_on
  entity_id: group.arrival