alias: Alert about UPS battery deactivation
initial_state: 'on'
trigger:
  platform: state
  entity_id: sensor.ups_status_data
  from: 'OB DISCHRG'
  for:
    seconds: 1
action:
  service: notify.mobile_app_little_ghost
  data:
    title: The Lair
    message: UPS battery power has deactivated, on line power
