alias: Turn off bedroom lights
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.aqara_lumi_motion_ac01_occupancy
  to: 'off'
  for:
    minutes: 3
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ now().time().strftime("%T") > states("input_datetime.lighting_on_time") }}'
    - condition: template
      value_template: "{{ is_state('input_select.cristians_state', 'Awake') }}"
action:
  service: homeassistant.turn_off
  entity_id: group.bedroom_lights
