alias: Turn on bedroom lights
initial_state: 'on'
trigger:
  device_id: 60dd1386f624b53fcf30f8e188a4804c
  domain: zha
  platform: device
  type: Enter
  subtype: sensor
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ now().time().strftime("%T") > states("input_datetime.lighting_on_time") }}'
    - condition: template
      value_template: "{{ is_state('input_select.cristians_state', 'Awake') }}"
action:
  service: homeassistant.turn_on
  entity_id: group.bedroom_lights
