alias: Turn off lights when leaving home
initial_state: 'on'
trigger:
  platform: state
  entity_id: device_tracker.cristian
  to: 'away'
  for:
    minutes: 5
action:
  service: homeassistant.turn_off
  entity_id: group.departure
