alias: Turn on the lights in the evening
initial_state: 'on'
trigger:
  platform: template
  value_template: '{{ now().time().strftime("%T") > states("input_datetime.lighting_on_time") }}'
condition:
    condition: state
    entity_id: 'device_tracker.cristian'
    state: 'home'
action:
  service: homeassistant.turn_on
  entity_id: group.lights_evening
