alias: Turn off office lights
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.motion_office
  to: 'off'
  for:
    minutes: 5
condition:
  condition: template
  value_template: '{{ now().time().strftime("%T") > states("input_datetime.lighting_on_time") }}'
action:
  service: homeassistant.turn_off
  entity_id: light.office_light
