alias: Toggle sleep mode asleep
initial_state: 'on'
trigger:
  event_data:
    command: button_single
    device_ieee: !secret button_bedroom_mac
  event_type: zha_event
  platform: event
condition:
    condition: template
    value_template: "{{ is_state('input_select.cristians_state', 'Awake') }}"
action:
  - service: light.turn_off
    entity_id: all
  - service: input_select.select_option
    data:
      entity_id: input_select.cristians_state
      option: Asleep
  - service: input_select.select_option
    data:
      entity_id: input_select.living_room_lighting_state
      option: 'Off'
