title: Home

views:
  # Home view
  - badges:
      - person.cristian
      - weather.the_lair
    cards:
      - cards:
          - entities:
              - entity: light.entrance_door_light
              - entity: light.ambient_light_kitchen
                name: Ambient Light (Kitchen)
              - entity: light.ambient_light_tv
              - entity: light.ambient_light_wall
                name: Ambient Light (Wall)
              - entity: light.dining_room_light
              - entity: light.window_light
              - entity: light.table_light
              - entity: light.office_light
              - entity: light.bathroom_light
                name: Bathroom Light
              - entity: light.right_nightstand_light
              - entity: light.left_nightstand_light
              - entity: group.garden_lights
                name: Garden Light
            title: Lights
            type: entities
        type: vertical-stack
    path: default_view
    title: Home
  # Living Room View
  - badges: []
    cards:
      - entities:
          - entity: group.living_room_lights
            type: 'custom:rgb-light-card'
            justify: center
            colors:
                - color_temp: 172 # 5800K Daylight
                  brightness: 255
                  transition: 0.5
                - color_temp: 266 # 3750K Cool
                  brightness: 255
                  transition: 0.5
                - color_temp: 318 # 3100K Warm
                  brightness: 255
                  transition: 0.5
                - color_temp: 400 # 2500K Ultra Warm
                  brightness: 255
                  transition: 0.5
        type: entities
      - cards:
        - entities:
          - entity:
          type: button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id:  script.living_room_lighting_mode_normal
          icon: 'mdi:brightness-7'
        - entities:
          - entity:
          type: button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id:  script.living_room_lighting_mode_romantic
          icon: 'mdi:heart'
        type: horizontal-stack
      - entities:
          - entity: light.ambient_light_wall
            name: Ambient Light (Wall)
          - entity: light.dining_room_light
          - entity: light.window_light
          - entity: light.table_light
        show_header_toggle: true
        title: Lights
        type: entities
    path: living_room
    title: Living Room
  # Kitchen view
  - badges: []
    cards:
      - entity: light.centralite_4257050rzhac_04ae3ef2_1
        name: Kettle
        type: entity-button
        icon: 'mdi:kettle'
      - entity: switch.osram_plug_01_00a26de0_3
        name: Coffee Grinder
        type: entity-button
        icon: 'mdi:coffee-maker'
      - entity: light.ambient_light_kitchen
        name: Ambient Light
        type: light
    path: kitchen
    title: Kitchen
  # Bedroom view
  - badges: []
    cards:
      - entity: light.right_nightstand_light
        name: Right Nightstand
        type: light
      - entity: light.left_nightstand_light
        name: Left Nightstand
        theme: default
        type: light
      - entity: sensor.bedroom_temperature
        type: sensor
        graph: none
    path: bedroom
    title: Bedroom
  # Office view
  - badges: []
    cards:
      - entity: light.office_light
        name: Desk
        type: entity-button
        icon: 'mdi:lightbulb'
      - entity: group.garden_lights
        name: Garden
        type: entity-button
        icon: 'mdi:lightbulb'
    path: office
    title: Office
  # Basement view
  - badges: []
    cards:
      - entity: light.ambient_light_tv
        name: Ambient Light (TV)
        type: light
      - entity: media_player.pioneer_avr
        type: media-control
      - entity: media_player.living_room_tv
        type: media-control
      - entity: media_player.kodi
        type: media-control
      - cards:
        - entities:
          - entity:
          type: button
          tap_action:
            action: call-service
            service: script.turn_on
            service_data:
              entity_id:  script.basement_lighting_mode_gaming
          icon: 'mdi:movie'
        type: horizontal-stack
    path: basement
    title: Basement
  # System view
  - badges: []
    cards:
      - entities:
        - sensor.uptime
        type: entities
      - cards:
        - entities:
          - entity: sensor.pi_hole_ads_blocked_today
          type: custom:mini-graph-card
          show:
            points: true
            labels: false
        - entities:
          - entity: sensor.speedtest_download
          - entity: sensor.speedtest_upload
          type: custom:mini-graph-card
        type: vertical-stack
      - entities:
        - entity: sensor.hydroquebec_yesterday_total_consumption
        name: Power Consumption
        hours_to_show: 168
        points_per_hour: 0.0417
        type: custom:mini-graph-card
        show:
          graph: bar
      - entities:
        - entity: sensor.nas_fan_rpm
          icon: 'mdi:fan'
        - entity: sensor.nas_temp_value
          name: Overall Temp
        - entity: sensor.nas_uptime
          icon: 'mdi:av-timer'
        - entity: sensor.nas_vol_1_free
          icon: 'mdi:chart-donut'
          name: Vol 1 Free Space
        - entity: sensor.nas_vol_1_size
          icon: 'mdi:harddisk'
          name: Vol 1 Total Space
        - entity: sensor.nas_vol_2_free
          icon: 'mdi:chart-donut'
          name: Vol 2 Free Space
        - entity: sensor.nas_vol_2_size
          icon: 'mdi:harddisk'
          name: Vol 2 Total Space
        show_header_toggle: false
        title: Netgear ReadyNAS
        type: entities
      - entities:
        - entity: sensor.motion_hallway_battery
          icon: 'mdi:motion-sensor'
          name: Hallway Motion Sensor
        - entity: sensor.motion_office_battery
          icon: 'mdi:motion-sensor'
          name: Office Motion Sensor
        - entity: sensor.motion_bedroom_battery
          icon: 'mdi:motion-sensor'
          name: Bedroom Motion Sensor
        - entity: sensor.button_living_room_battery
          icon: 'mdi:toggle-switch'
          name: Living Room Button
        - entity: sensor.button_bedroom_battery
          icon: 'mdi:toggle-switch'
          name: Bedroom Button
        show_header_toggle: false
        title: Battery Levels
        type: entities
    path: system
    title: System
  # Halloween view
  # - badges: []
  #   cards:
  #     - entity: sensor.falconplayer_falcon_player_status
  #       name: Falcon Player
  #       type: sensor
  #     - entity: script.halloween_stop
  #       name: Stop
  #       type: entity-button
  #       tap_action:
  #         action: call-service
  #         service: script.halloween_stop
  #       icon: 'mdi:stop'
  #     - entity: script.halloween_blood
  #       name: Blood
  #       type: entity-button
  #       tap_action:
  #         action: call-service
  #         service: script.halloween_blood
  #       icon: 'mdi:water-outline'
  #     - entity: script.halloween_eyes
  #       name: Eyes
  #       type: entity-button
  #       tap_action:
  #         action: call-service
  #         service: script.halloween_eyes
  #       icon: 'mdi:eye-outline'
  #     - entity: script.halloween_monsters
  #       name: Monsters
  #       type: entity-button
  #       tap_action:
  #         action: call-service
  #         service: script.halloween_monsters
  #       icon: 'mdi:coffin'
  #     - entity: script.halloween_zombies
  #       name: Zombies
  #       type: entity-button
  #       tap_action:
  #         action: call-service
  #         service: script.halloween_zombies
  #       icon: 'mdi:emoticon-dead'
  #     - entity: script.halloween_ghosts
  #       name: ghosts
  #       type: entity-button
  #       tap_action:
  #         action: call-service
  #         service: script.halloween_ghosts
  #       icon: 'mdi:ghost'
  #   path: halloween
  #   title: Halloween
