- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - minutely_summary
    - hourly_summary
    - daily_summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone

- platform: template
  sensors:
    hall_temperature:
      friendly_name: "Hall Temp"
      unit_of_measurement: '°C'
      value_template: "{{ ((((((states('sensor.smartthings_motionv4_0102c904_1_1026')|float) + (states('sensor.smartthings_motionv5_010acf87_1_1026')|float))/2)|float)| round(0))|int) }}"

- platform: pi_hole
  host: !secret pi_hole
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today
    - queries_cached
    - queries_forwarded

- platform: teksavvy
  api_key: !secret teksavvy_api_key
  total_bandwidth: 0
  monitored_variables:
    - usage_gb
    - onpeak_download
    - onpeak_upload
    - onpeak_total
    - offpeak_download
    - offpeak_upload
    - offpeak_total

- platform: snmp
  host: !secret nas
  community: !secret snmp_community
  baseoid: 1.3.6.1.2.1.25.1.1.0
  name: 'NAS Uptime'
  value_template: >-
    {% set time = (value | int) | int %}
    {% set minutes = ((time % 360000) / 6000) | int%}
    {% set hours = ((time % 8640000) / 360000) | int %}
    {% set days = (time / 8640000) | int %}
      {%- if time < 60 -%}
        Less than 1 min
        {%- else -%}
        {%- if days > 0 -%}
          {{ days }}d
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if days > 0 -%}
            {{ ' ' }}
          {%- endif -%}
          {{ hours }}hr
        {%- endif -%}
        {%- if minutes > 0 -%}
          {%- if days > 0 or hours > 0 -%}
            {{ ' ' }}
          {%- endif -%}
          {{ minutes }}min
        {%- endif -%}
      {%- endif -%}

- platform: snmp
  host: !secret nas
  community: !secret snmp_community
  baseoid: 1.3.6.1.2.1.1.5.0
  name: 'NAS Host Name'

- platform: snmp
  host: !secret nas
  community: !secret snmp_community
  baseoid: 1.3.6.1.4.1.4526.22.4.1.2.1
  unit_of_measurement: 'RPM'
  name: 'NAS Fan RPM'

- platform: snmp
  host: !secret nas
  community: !secret snmp_community
  baseoid: 1.3.6.1.4.1.4526.22.5.1.2.1
  unit_of_measurement: '°C'
  name: 'NAS Temp Value'
    
- platform: snmp
  host: !secret nas
  community: !secret snmp_community
  baseoid: 1.3.6.1.4.1.4526.22.7.1.5.1
  name: 'NAS Vol 1 Size'
  value_template: >-
    {% set val = value | int %}
    {% set size = ((val * 0.954) / 1000000 | float) | round(2) %}
    {{ size }} TB

- platform: snmp
  host: !secret nas
  community: !secret snmp_community
  baseoid: 1.3.6.1.4.1.4526.22.7.1.6.1
  name: 'NAS Vol 1 Free'
  value_template: >-
    {% set val = value | int %}
    {% set size = ((val * 0.954) / 1000000 | float) | round(2) %}
    {{ size }} TB

- platform: snmp
  host: !secret nas
  community: !secret snmp_community
  baseoid: 1.3.6.1.4.1.4526.22.7.1.5.2
  name: 'NAS Vol 2 Size'
  value_template: >-
    {% set val = value | int %}
    {% set size = ((val * 0.954) / 1000000 | float) | round(2) %}
    {{ size }} TB

- platform: snmp
  host: !secret nas
  community: !secret snmp_community
  baseoid: 1.3.6.1.4.1.4526.22.7.1.6.2
  name: 'NAS Vol 2 Free'
  value_template: >-
    {% set val = value | int %}
    {% set size = ((val * 0.954) / 1000000 | float) | round(2) %}
    {{ size }} TB

- platform: hydroquebec
  username: !secret hydroquebec_user
  password: !secret hydroquebec_pwd
  contract: !secret hydroquebec_contract
  monitored_variables:
    - yesterday_total_consumption
    - period_total_consumption
    - period_mean_daily_bill

- platform: uptime
